name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Make 00 check
      run: make -C ex00/

    - name: Make 01 check
      run: make -C ex01/

    - name: Make 02 check
      run: make -C ex02/

    - name: Make 03 check
      run: make -C ex03/

    - name: Make 04 check
      run: make -C ex04/

    - name: Make 05 check
      run: make -C ex05/

    
