name: Ubuntu Compilation

on:
  push:
    branches: [ "master" ]

env:
  DIR: 00 01 02
  EXO: ex00 ex01 ex02 ex03 ex04 ex05

jobs:
  check-c98:
    name: Compiling using ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Loop, search and compile
        run: |
          for i in ${{ env.DIR }}; do
            for n in ${{ env.EXO }}; do
              if [[ $(find ${i}/${n}) -eq 0 ]]; then
                echo "Path: ${i}/${n}"
                v=$(find ${i}/${n})
                # make -C ${v}
              fi
            done
          done
