name: Ubuntu Compilation

on:
  push:
    branches: [ "master" ]

env:
  DIR: 00 01 02
  EXO: ex00 ex01 ex02 ex03 ex04 ex05
  CC: c++
  MAKE: make

jobs:
  check-c98:
    name: Compiling using ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          fetch-depth: 3
      - name: Build makefiles
        # run: | 
        #   dir
        #   make
        run: |
          for i in ${{ env.DIR }}; do
            for n in ${{ env.EXO }}; do
              if [[ $(find ${i}/${n}) ]]; then
                echo "Path: ${i}/${n}"
                v=$(find ${i}/${n})
                dir ${v}
                make -C ${v}
                dir ${v}
              fi
            done
          done
