name: Ubuntu Compilation

on:
  push:
    branches: [ "master" ]

env:
  DIR: 00 01 02
  EXO: ex00 ex01 ex02 ex03 ex04 ex05

jobs:
  check-c98:
    name: Compiling using ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: Build makefiles
        run: | 
          dir
          make
        # run: |
        #   for i in ${{ env.DIR }}; do
        #     for n in ${{ env.EXO }}; do
        #       if [[ $(find ${i}/${n}) ]]; then
        #         dir ${i}/${n}
        #         echo "Path: ${i}/${n}"
        #         v=$(find ${i}/${n})
        #         make re -C ${v}
        #       fi
        #     done
        #   done
