name: CPP Flag Check

on:
  push:
    branches: [ "master" ]

env:
  DIR: 00 01 02 03 04 05 06 07 08
  EXO: ex00 ex01 ex02 ex03 ex04 ex05
  CC: c++
  MAKE: make

jobs:
  check-c98:
    name: Compiling using ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          fetch-depth: 3
      - name: Build 00
        working-directory: 00/
        continue-on-error: true
        run: |
          for n in ${{ env.EXO }}; do
            if [[ -f ${n}/Makefile ]]; then
              make -kj re -C ${n}
            fi
          done
      - name: Build 01
        working-directory: 01/
        continue-on-error: true
        run: |
          for n in ${{ env.EXO }}; do
            if [[ -f ${n}/Makefile ]]; then
              make -kj re -C ${n}
            fi
          done
      - name: Build 02
        working-directory: 02/
        continue-on-error: true
        run: |
          for n in ${{ env.EXO }}; do
            if [[ -f ${n}/Makefile ]]; then
              make -kj re -C ${n}
            fi
          done
      - name: Build 03
        working-directory: 03/
        continue-on-error: true
        run: |
          for n in ${{ env.EXO }}; do
            if [[ -f ${n}/Makefile ]]; then
              make -kj re -C ${n}
            fi
          done
      - name: Build 04
        working-directory: 04/
        continue-on-error: true
        run: |
          for n in ${{ env.EXO }}; do
            if [[ -f ${n}/Makefile ]]; then
              make -kj re -C ${n}
            fi
          done
      - name: Build 05
        working-directory: 05/
        continue-on-error: true
        run: |
          for n in ${{ env.EXO }}; do
            if [[ -f ${n}/Makefile ]]; then
              make -kj re -C ${n}
            fi
          done
      - name: Build 06
        working-directory: 06/
        continue-on-error: true
        run: |
          for n in ${{ env.EXO }}; do
            if [[ -f ${n}/Makefile ]]; then
              make -kj re -C ${n}
            fi
          done
      - name: Build 07
        working-directory: 07/
        continue-on-error: true
        run: |
          for n in ${{ env.EXO }}; do
            if [[ -f ${n}/Makefile ]]; then
              make -kj re -C ${n}
            fi
          done
      - name: Build 08
        working-directory: 08/
        continue-on-error: true
        run: |
          for n in ${{ env.EXO }}; do
            if [[ -f ${n}/Makefile ]]; then
              make -kj re -C ${n}
            fi
          done

