name: Makefile CI

# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        ex: [ex00, ex01, ex02, ex03, ex04, ex05, ex06]
        dir: [00, 01, 02, 03]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with: ${{ matrix }}
    
    - if: ${{ matrix.dir[0] }}
      run: for i in "${matrix.dir[@]}"; do
              for n in "${matrix.ex[@]}"; do
                make -C "${matrix.dir[i]}"/${matrix.ex[n]}
              done
            done
          # make -C ex00/

    # - name: Make 00 check

    - name: Make 01 check
      run: make -C ex01/
    
