name: Loop

on:
  push:
    branches: [ "master" ]

env:
  DIR: '00/,01/,02/'
  EXO: 'ex00/,ex01/,ex02/,ex03/,ex04/,ex05/'

jobs:
  run-my-stuff:
    name: Iterating over comma-separated-values
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Echo values from ENV
        run: |
          IFS="," read -a module <<< ${{ env.DIR }}
          IFS="," read -a exo <<< ${{ env.EXO }}
          for i in "${module[@]}"; do
            echo "Value: ${i}"
            echo "Value: ${i%.*}"
          done
          for i in "${exo[@]}"; do
            echo "Value: ${i}"
            echo "Value: ${i%.*}"
          done

      - uses: actions/checkout@master
      - name: Finding files and store to output
        id: finding-files
        run: echo "FILELIST=$(find . -name 'Makefile' -print | tr '\n' ' ')" >> $GITHUB_OUTPUT
          # echo "::set-output name=FILELIST::$(find . -name '*.md' -print)"

      - uses: actions/checkout@master
      - name: Processing my found files from output
        run: |
          IFS="," read -a makefile_path <<< ${{ steps.finding-files.outputs.FILELIST }}
          for i in "${makefile_path[@]}"; do
            file_path=$(dirname "${i}")
            file_name=$(basename "${i}")
            make -C ${i}
            cd file_path
            cat file_name
          done
