name: Iterate

on:
  push:
    branches: [ "master" ]

env:
  DIR: '00/, 01/, 02/'
  EXO: 'ex00/, ex01/, ex02/, ex03/, ex04/, ex05/'

jobs:
  run-my-stuff:
    name: Iterating over comma-separated-values
    runs-on: ubuntu-latest
    steps:
      - name: Echo values from ENV
        run: |
          for i in "${env.DIR[@]}"; do
            for n in "${env.EXO[@]}"; do
              echo "Value: ${i}"
              echo "Value: ${n}"
            done
          done
      - name: Finding files and store to output
        id: finding-files
        run: |
          echo "::set-output name=FILELIST::$(find . -name 'ex0*/' -print)"
      - name: Processing my found files from output
        run: |
          IFS="," read -a myarray <<< ${{ steps.finding-files.outputs.FILELIST }}
          for i in "${myarray[@]}"; do
            file_path=$(dirname "${i}")
            file_name=$(basename "${i}")
            cd file_path
            cat file_name
          done